// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "登录前",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "handler"
                ],
                "summary": "首页",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Fundmt"
                        }
                    }
                }
            }
        },
        "/board": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "date"
                ],
                "summary": "查看某一天的未完成计划和图片",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SchAndPh"
                        }
                    }
                }
            }
        },
        "/board/searchdate": {
            "post": {
                "description": "输入年月日",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "date"
                ],
                "summary": "查日期",
                "parameters": [
                    {
                        "type": "string",
                        "description": "年",
                        "name": "year",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "月",
                        "name": "month",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "日",
                        "name": "day",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SetDate"
                        }
                    }
                }
            }
        },
        "/calendar": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "查看某天的任务",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SchAndPh"
                        }
                    }
                }
            }
        },
        "/calendar/addphoto": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "photo"
                ],
                "summary": "添加图片",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片",
                        "name": "photo",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Url"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Fundmt"
                        }
                    }
                }
            }
        },
        "/calendar/addphoto2": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "photo"
                ],
                "summary": "添加图片2",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片",
                        "name": "photo",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Url"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Fundmt"
                        }
                    }
                }
            }
        },
        "/calendar/addphoto3": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "photo"
                ],
                "summary": "添加图片3",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片",
                        "name": "photo",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Url"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Fundmt"
                        }
                    }
                }
            }
        },
        "/calendar/addphoto4": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "photo"
                ],
                "summary": "添加图片4",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片",
                        "name": "photo",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Url"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Fundmt"
                        }
                    }
                }
            }
        },
        "/calendar/check/{content}": {
            "put": {
                "description": "点击实现完成或取消完成",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "完成某日程",
                "parameters": [
                    {
                        "type": "string",
                        "description": "某个日程",
                        "name": "content",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Fundmt"
                        }
                    }
                }
            }
        },
        "/calendar/memory": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "date"
                ],
                "summary": "纪念某一天",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Fundmt"
                        }
                    }
                }
            }
        },
        "/calendar/write": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "写日程",
                "parameters": [
                    {
                        "type": "string",
                        "description": "日程内容",
                        "name": "content",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Fundmt"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Fundmt"
                        }
                    }
                }
            }
        },
        "/crash": {
            "get": {
                "description": "里面有近14天已完成的任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedule"
                ],
                "summary": "回收站",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Sch"
                        }
                    }
                }
            }
        },
        "/index": {
            "get": {
                "description": "登陆后",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "handler"
                ],
                "summary": "首页2",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Mem"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "使用一站式",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "type": "string",
                        "name": "password",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "uid",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Token"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Fundmt"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Fundmt"
                        }
                    },
                    "402": {
                        "description": "Payment Required",
                        "schema": {
                            "$ref": "#/definitions/model.Fundmt"
                        }
                    }
                }
            }
        },
        "/preview/{year}/{month}/{day}": {
            "get": {
                "description": "查看当天的图片与做完的任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "door"
                ],
                "summary": "打开任意门",
                "parameters": [
                    {
                        "type": "string",
                        "description": "年",
                        "name": "year",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "月",
                        "name": "month",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "日",
                        "name": "day",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.SchAndPh"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Fundmt": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "model.Mem": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "ifMemory": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "model.Sch": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "schedule": {
                    "description": "我感觉这里的数据类型是要改的//明早再说好了",
                    "type": "object",
                    "properties": {
                        "content": {
                            "type": "string"
                        },
                        "day": {
                            "type": "integer"
                        },
                        "done": {
                            "type": "boolean"
                        },
                        "month": {
                            "type": "integer"
                        },
                        "userId": {
                            "type": "string"
                        },
                        "year": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "model.SchAndPh": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "photo": {
                    "type": "object",
                    "properties": {
                        "day": {
                            "type": "integer"
                        },
                        "insertTime": {
                            "type": "string"
                        },
                        "month": {
                            "type": "integer"
                        },
                        "number": {
                            "type": "integer"
                        },
                        "photoUrl": {
                            "type": "string"
                        },
                        "userId": {
                            "type": "string"
                        },
                        "year": {
                            "type": "integer"
                        }
                    }
                },
                "schedule": {
                    "description": "我感觉这里的数据类型是要改的//明早再说好了",
                    "type": "object",
                    "properties": {
                        "content": {
                            "type": "string"
                        },
                        "day": {
                            "type": "integer"
                        },
                        "done": {
                            "type": "boolean"
                        },
                        "month": {
                            "type": "integer"
                        },
                        "userId": {
                            "type": "string"
                        },
                        "year": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "model.SetDate": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "day": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "month": {
                    "type": "integer"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "model.Token": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "model.Url": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "library API",
	Description:      "我的日程本API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
